// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOsSVTuZ-69aBIhJfqLmaUtmv0eQSVNuI',
    appId: '1:88169992530:web:7f8c326c982af8ed5d6a8b',
    messagingSenderId: '88169992530',
    projectId: 'taskapp-619da',
    authDomain: 'taskapp-619da.firebaseapp.com',
    storageBucket: 'taskapp-619da.appspot.com',
    measurementId: 'G-VD87SGVCBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxERoZ14OADWZ4uKaXp9H-RR1EGEUHJ3o',
    appId: '1:88169992530:android:7096adbfbee0c8525d6a8b',
    messagingSenderId: '88169992530',
    projectId: 'taskapp-619da',
    storageBucket: 'taskapp-619da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdsYgH7-B2G_PcjwCr3D5Iq3ilReenskg',
    appId: '1:88169992530:ios:af045b9e55f0a7815d6a8b',
    messagingSenderId: '88169992530',
    projectId: 'taskapp-619da',
    storageBucket: 'taskapp-619da.appspot.com',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdsYgH7-B2G_PcjwCr3D5Iq3ilReenskg',
    appId: '1:88169992530:ios:b62d85384e13912d5d6a8b',
    messagingSenderId: '88169992530',
    projectId: 'taskapp-619da',
    storageBucket: 'taskapp-619da.appspot.com',
    iosBundleId: 'com.example.taskapp.RunnerTests',
  );
}
